# Generated by Django 2.2.1 on 2019-05-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercode', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('deptname', models.CharField(max_length=30)),
                ('deptcode', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phonenum', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
