# Generated by Django 2.2.1 on 2019-06-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodle', '0002_myphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='tongxunlu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuan', models.CharField(max_length=30)),
                ('xi', models.CharField(max_length=30)),
                ('zhuanye', models.CharField(max_length=30)),
                ('erjizhuanye', models.CharField(max_length=30, null=True)),
                ('xingming', models.CharField(max_length=30, null=True)),
                ('zhiwu', models.CharField(max_length=30, null=True)),
                ('zhize', models.CharField(max_length=500, null=True)),
                ('dianhua', models.CharField(max_length=30, null=True)),
                ('dizhi', models.CharField(max_length=30, null=True)),
                ('youxiang', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
