# Generated by Django 2.2.1 on 2019-06-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodle', '0003_tongxunlu'),
    ]

    operations = [
        migrations.CreateModel(
            name='yuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('has_son', models.CharField(max_length=1, null=True)),
                ('has_father', models.CharField(max_length=1, null=True)),
                ('father_name', models.CharField(max_length=30, null=True)),
                ('son_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
